// SPOTS
export const RECEIVE_SPOT = "RECEIVE_SPOT";
export const RECEIVE_SPOTS = "RECEIVE_SPOTS";
export const RECEIVE_SPOT_FORECAST = "RECEIVE_SPOT_FORECAST";
export const RECEIVE_SPOT_WEATHER = "RECEIVE_SPOT_WEATHER";
export const FETCH_SPOT_FORECAST = "FETCH_SPOT_FORECAST";
export const FETCH_SPOT_WEATHER = "FETCH_SPOT_WEATHER";

// COUNTIES
export const RECEIVE_COUNTY_FORECAST = "RECEIVE_COUNTY_FORECAST";
export const FETCH_COUNTY_FORECAST = "FETCH_COUNTY_FORECAST";