// SPOTS
export const RECEIVE_SPOT = "RECEIVE_SPOT";
export const RECEIVE_SPOTS = "RECEIVE_SPOTS";
export const RECEIVE_SPOT_FORECAST = "RECEIVE_SPOT_FORECAST";
export const RECEIVE_SPOT_WEATHER = "RECEIVE_SPOT_WEATHER";
export const FETCH_SPOT_FORECAST = "FETCH_SPOT_FORECAST";
export const FETCH_SPOT_WEATHER = "FETCH_SPOT_WEATHER";
export const RECEIVE_SEARCH_RESULTS = "RECEIVE_SEARCH_RESULTS";

// COUNTIES
export const RECEIVE_COUNTY_FORECAST = "RECEIVE_COUNTY_FORECAST";
export const FETCH_COUNTY_FORECAST = "FETCH_COUNTY_FORECAST";

// SESSIONS
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const RECEIVE_AUTH_ERRORS = "RECEIVE_AUTH_ERRORS";
export const RECEIVE_CURRENT_USER = "RECEIVE_CURRENT_USER";